// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderWithDeletion from "./components/HeaderWithDeletion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Captiv8",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-purple-500 to-blue-500 min-h-screen text-white`}
      >
        <main className="p-4 max-w-2xl mx-auto">
          <HeaderWithDeletion />
          {children}
        </main>
      </body>
    </html>
  );
}
